### ISSUE TITLE
`chooser` branch not deployed to stateofthemap.org, yet

### ISSUE THREAD

**Issue by YaguraStation** [openstreetmap/stateofthemap-website#4]
`chooser` branch including https://github.com/openstreetmap/stateofthemap/commit/15d7307486d2c86b08087618690e2263fd9855fd not deployed to stateofthemap.org, yet

As a reminder. In case this is not the expected behaviour.

**Comment by tomhughes** [comment]
Well that's what you get for trying to do it yourselves instead of waiting for me ;-) I assumed @Firefishy knew what he was doing so didn't check after I saw he merged it.

**Comment by tomhughes** [comment]
I have deployed it properly now - it should be up within half an hour.

**Comment by Firefishy** [comment]
Woops, sorry. Yeah I forgot I had to manually merge back to https://git.openstreetmap.org/stateofthemap.git
